version: '3'
services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
    ports:
      - "8085:8085"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  notification-service:
    image: notification-service
    container_name: notification-service
    depends_on:
      - eureka-server
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_APPLICATION_NAME=notification-service
      - SERVER_PORT=8084

  user-service:
    image: user-service
    container_name: user-service
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_APPLICATION_NAME=user-service
      - SERVER_PORT=8083

  task-service:
    image: task-service
    container_name: task-service
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_APPLICATION_NAME=task-service
      - SERVER_PORT=8082
